//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nilnul.num.real._Ken._web.rhiemannHypothesis.claims.eulerProductionEqZeta._ctrs
{


	public partial class InverseOfNToS_toolboxData
	{
	}
}
